#!/bin/sh
# Example only. Do not edit this file for real use and never commit real values.
#
# Write the private configuration with:
#   sh scripts/setup.sh --device "Your Android device name"
#
# It is stored mode-600 under:
#   $XDG_CONFIG_HOME/competitor-screenshot-insights-android/agent-device-env.sh
#   ~/.config/competitor-screenshot-insights-android/agent-device-env.sh

AGENT_DEVICE_NODE_BIN="/absolute/path/to/node/bin"
AGENT_DEVICE_BIN="/absolute/path/to/agent-device/bin"
ANDROID_HOME="/absolute/path/to/Android/sdk"
ANDROID_SDK_ROOT="/absolute/path/to/Android/sdk"
CSI_ADB_BIN="/absolute/path/to/Android/sdk/platform-tools/adb"
AGENT_DEVICE_PLATFORM="android"
AGENT_DEVICE_DEVICE="Your Android device name"
# Optional. Set only when several Android devices are attached.
AGENT_DEVICE_SERIAL=""
AGENT_DEVICE_SESSION="phone-main"
SCREENSHOT_STITCHER_HOME="/absolute/path/to/screenshot-stitcher"
SCREENSHOT_STITCHER_PYTHON="/absolute/path/to/screenshot-stitcher/bin/python"
SCREENSHOT_STITCHER_BIN="/absolute/path/to/screenshot-stitcher/bin/screenshot-stitcher"
# Coordinate fallback stays disabled unless BOTH are verified on this device.
CSI_VIEWPORT_WIDTH=""
CSI_VIEWPORT_HEIGHT=""
